; PlatformIO Project Configuration File
[env:fishbot]
platform = espressif32
board = esp32dev
framework = arduino

# 回归 Serial 模式，使用国内镜像
board_build_microros_transport = serial
lib_deps = 
    https://gitee.com/ohhuo/micro_ros_platformio.git
    SCServo
    madhephaestus/ESP32Servo @ ^1.1.8

monitor_speed = 115200
